/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as AuthImport } from './routes/_auth'
import { Route as R404Import } from './routes/__404'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as ProtectedServersIndexImport } from './routes/_protected/servers/index'
import { Route as ProtectedServersServerIdImport } from './routes/_protected/servers/$serverId'
import { Route as AuthAuthSignupImport } from './routes/_auth/auth/signup'
import { Route as AuthAuthSigninImport } from './routes/_auth/auth/signin'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const R404Route = R404Import.update({
  id: '/__404',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SettingsIndexRoute = SettingsIndexImport.update({
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedServersIndexRoute = ProtectedServersIndexImport.update({
  path: '/servers/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedServersServerIdRoute = ProtectedServersServerIdImport.update({
  path: '/servers/$serverId',
  getParentRoute: () => ProtectedRoute,
} as any)

const AuthAuthSignupRoute = AuthAuthSignupImport.update({
  path: '/auth/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAuthSigninRoute = AuthAuthSigninImport.update({
  path: '/auth/signin',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/__404': {
      id: '/__404'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth/signin': {
      id: '/_auth/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthSigninImport
      parentRoute: typeof AuthImport
    }
    '/_auth/auth/signup': {
      id: '/_auth/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_protected/servers/$serverId': {
      id: '/_protected/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ProtectedServersServerIdImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/servers/': {
      id: '/_protected/servers/'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ProtectedServersIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AuthRoute: AuthRoute.addChildren({
    AuthAuthSigninRoute,
    AuthAuthSignupRoute,
  }),
  ProtectedRoute: ProtectedRoute.addChildren({
    ProtectedServersServerIdRoute,
    ProtectedServersIndexRoute,
  }),
  AboutLazyRoute,
  SettingsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__404",
        "/_auth",
        "/_protected",
        "/about",
        "/settings/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/__404": {
      "filePath": "__404.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth/signin",
        "/_auth/auth/signup"
      ]
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/servers/$serverId",
        "/_protected/servers/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/_auth/auth/signin": {
      "filePath": "_auth/auth/signin.tsx",
      "parent": "/_auth"
    },
    "/_auth/auth/signup": {
      "filePath": "_auth/auth/signup.tsx",
      "parent": "/_auth"
    },
    "/_protected/servers/$serverId": {
      "filePath": "_protected/servers/$serverId.tsx",
      "parent": "/_protected"
    },
    "/_protected/servers/": {
      "filePath": "_protected/servers/index.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
