/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as AuthAuthSigninRouteImport } from './routes/_auth/auth/signin'
import { Route as AuthAuthSignupRouteImport } from './routes/_auth/auth/signup'
import { Route as ProtectedServersIndexRouteImport } from './routes/_protected/servers/index'
import { Route as ProtectedServersServerIdRouteImport } from './routes/_protected/servers/$serverId'

const IndexLazyRouteImport = createFileRoute('/')()
const AboutLazyRouteImport = createFileRoute('/about')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthSigninRoute = AuthAuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthSignupRoute = AuthAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedServersIndexRoute = ProtectedServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedServersServerIdRoute =
  ProtectedServersServerIdRouteImport.update({
    id: '/servers/$serverId',
    path: '/servers/$serverId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/settings/': typeof SettingsIndexRoute
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/servers/$serverId': typeof ProtectedServersServerIdRoute
  '/servers/': typeof ProtectedServersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/settings': typeof SettingsIndexRoute
  '/auth/signin': typeof AuthAuthSigninRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/servers/$serverId': typeof ProtectedServersServerIdRoute
  '/servers': typeof ProtectedServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/settings/': typeof SettingsIndexRoute
  '/_auth/auth/signin': typeof AuthAuthSigninRoute
  '/_auth/auth/signup': typeof AuthAuthSignupRoute
  '/_protected/servers/$serverId': typeof ProtectedServersServerIdRoute
  '/_protected/servers/': typeof ProtectedServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/settings/'
    | '/auth/signin'
    | '/auth/signup'
    | '/servers/$serverId'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/settings'
    | '/auth/signin'
    | '/auth/signup'
    | '/servers/$serverId'
    | '/servers'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/about'
    | '/settings/'
    | '/_auth/auth/signin'
    | '/_auth/auth/signup'
    | '/_protected/servers/$serverId'
    | '/_protected/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/signin': {
      id: '/_auth/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/signup': {
      id: '/_auth/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/servers/': {
      id: '/_protected/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ProtectedServersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/servers/$serverId': {
      id: '/_protected/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ProtectedServersServerIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthSigninRoute: typeof AuthAuthSigninRoute
  AuthAuthSignupRoute: typeof AuthAuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthSigninRoute: AuthAuthSigninRoute,
  AuthAuthSignupRoute: AuthAuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedServersServerIdRoute: typeof ProtectedServersServerIdRoute
  ProtectedServersIndexRoute: typeof ProtectedServersIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedServersServerIdRoute: ProtectedServersServerIdRoute,
  ProtectedServersIndexRoute: ProtectedServersIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
